import { FormField, FormTemplate } from '../types';

export const ADAL_TEMPLATE_ID = 'adal_guest_book_2026';

export function getAdalDefaultFields(): FormField[] {
  return [
    // -------------------------------------------------------------
    // PAGE 1 FIELDS
    // -------------------------------------------------------------
    // Top-Right PROJECT box: drawing / sketch / photo / text area
    {
      id: 'p1_project_box',
      type: 'signature', // allows tablet pen/finger drawing & sketch
      label: 'PROJECT sketch / note',
      page: 1,
      x: 47.0,
      y: 4.24,
      width: 42.5,
      height: 18.39,
      placeholder: 'Click or use stylus / touch to sketch project...',
    },
    // Date
    {
      id: 'p1_date',
      type: 'text',
      label: 'Date',
      page: 1,
      x: 15.5,
      y: 24.2,
      width: 23.5,
      height: 2.3,
      placeholder: 'e.g. 04.11.2026',
    },
    // Contact Person
    {
      id: 'p1_contact_person',
      type: 'text',
      label: 'Contact Person',
      page: 1,
      x: 54.0,
      y: 24.2,
      width: 35.5,
      height: 2.3,
      placeholder: 'e.g. John Smith',
    },
    // Country
    {
      id: 'p1_country',
      type: 'text',
      label: 'Country',
      page: 1,
      x: 18.5,
      y: 28.3,
      width: 24.0,
      height: 2.3,
      placeholder: 'e.g. France / Poland',
    },
    // Company Name
    {
      id: 'p1_company_name',
      type: 'text',
      label: 'Company Name',
      page: 1,
      x: 57.5,
      y: 28.3,
      width: 32.0,
      height: 2.3,
      placeholder: 'Company name',
    },
    // Email
    {
      id: 'p1_email',
      type: 'text',
      label: 'Email',
      page: 1,
      x: 16.0,
      y: 32.35,
      width: 33.5,
      height: 2.3,
      placeholder: 'contact@company.com',
    },
    // Phone
    {
      id: 'p1_phone',
      type: 'text',
      label: 'Phone',
      page: 1,
      x: 57.0,
      y: 32.35,
      width: 32.5,
      height: 2.3,
      placeholder: '+33 600 000 000',
    },
    // Catalogue to send: Digital
    {
      id: 'p1_cat_digital',
      type: 'checkbox',
      label: 'Digital catalogue',
      page: 1,
      x: 28.8,
      y: 37.62,
      width: 1.8,
      height: 1.27,
    },
    // Catalogue to send: Printed
    {
      id: 'p1_cat_printed',
      type: 'checkbox',
      label: 'Printed catalogue',
      page: 1,
      x: 38.8,
      y: 37.62,
      width: 1.8,
      height: 1.27,
    },
    // Catalogue: Christmas trees & greenery products
    {
      id: 'p1_cat_trees',
      type: 'checkbox',
      label: 'Christmas trees & greenery',
      page: 1,
      x: 51.0,
      y: 37.62,
      width: 1.8,
      height: 1.27,
    },
    // Catalogue: Decor products
    {
      id: 'p1_cat_decor',
      type: 'checkbox',
      label: 'Decor products',
      page: 1,
      x: 77.4,
      y: 37.62,
      width: 1.8,
      height: 1.27,
    },
    // Adress line 1
    {
      id: 'p1_address_1',
      type: 'text',
      label: 'Adress line 1',
      page: 1,
      x: 22.0,
      y: 40.49,
      width: 67.5,
      height: 2.3,
      placeholder: 'Street address, building / suite...',
    },
    // Adress line 2
    {
      id: 'p1_address_2',
      type: 'text',
      label: 'Adress line 2',
      page: 1,
      x: 22.0,
      y: 44.45,
      width: 67.5,
      height: 2.3,
      placeholder: 'Postal code, city, region...',
    },
    // Are you interested in seasonal decorations?: Yes
    {
      id: 'p1_seasonal_yes',
      type: 'checkbox',
      label: 'Seasonal: Yes',
      page: 1,
      x: 53.0,
      y: 49.50,
      width: 1.8,
      height: 1.27,
    },
    // Are you interested in seasonal decorations?: No
    {
      id: 'p1_seasonal_no',
      type: 'checkbox',
      label: 'Seasonal: No',
      page: 1,
      x: 61.3,
      y: 49.50,
      width: 1.8,
      height: 1.27,
    },
    // Seasonal: Valentine’s Day
    {
      id: 'p1_seasonal_val',
      type: 'checkbox',
      label: "Valentine's Day",
      page: 1,
      x: 11.0,
      y: 53.04,
      width: 1.8,
      height: 1.27,
    },
    // Seasonal: Easter
    {
      id: 'p1_seasonal_easter',
      type: 'checkbox',
      label: 'Easter',
      page: 1,
      x: 27.7,
      y: 53.04,
      width: 1.8,
      height: 1.27,
    },
    // Seasonal: Spring
    {
      id: 'p1_seasonal_spring',
      type: 'checkbox',
      label: 'Spring',
      page: 1,
      x: 41.7,
      y: 53.04,
      width: 1.8,
      height: 1.27,
    },
    // Seasonal: Summer
    {
      id: 'p1_seasonal_summer',
      type: 'checkbox',
      label: 'Summer',
      page: 1,
      x: 54.7,
      y: 53.04,
      width: 1.8,
      height: 1.27,
    },
    // Seasonal: Halloween
    {
      id: 'p1_seasonal_halloween',
      type: 'checkbox',
      label: 'Halloween',
      page: 1,
      x: 68.0,
      y: 53.04,
      width: 1.8,
      height: 1.27,
    },
    // Seasonal: Autumn
    {
      id: 'p1_seasonal_autumn',
      type: 'checkbox',
      label: 'Autumn',
      page: 1,
      x: 82.4,
      y: 53.04,
      width: 1.8,
      height: 1.27,
    },
    // Would you like to visit showroom?: Yes
    {
      id: 'p1_visit_yes',
      type: 'checkbox',
      label: 'Visit showroom: Yes',
      page: 1,
      x: 53.0,
      y: 57.14,
      width: 1.8,
      height: 1.27,
    },
    // Would you like to visit showroom?: No
    {
      id: 'p1_visit_no',
      type: 'checkbox',
      label: 'Visit showroom: No',
      page: 1,
      x: 61.3,
      y: 57.14,
      width: 1.8,
      height: 1.27,
    },
    // Preferred time period
    {
      id: 'p1_visit_period',
      type: 'text',
      label: 'Preferred time period',
      page: 1,
      x: 41.5,
      y: 59.37,
      width: 48.0,
      height: 2.3,
      placeholder: 'e.g. Spring 2027 / Q2',
    },
    // Page 1 Notes / Project Ideas textarea
    {
      id: 'p1_notes',
      type: 'textarea',
      label: 'Notes / Project Ideas (Page 1)',
      page: 1,
      x: 10.5,
      y: 67.0,
      width: 79.0,
      height: 27.5,
      placeholder: 'Enter project notes, sketches description, and client ideas...',
      fontSize: 12,
      lineHeight: 1.35,
    },

    // -------------------------------------------------------------
    // PAGE 2 FIELDS
    // -------------------------------------------------------------
    // Page 2 Notes / Project Ideas
    {
      id: 'p2_notes',
      type: 'textarea',
      label: 'Notes / Project Ideas (Page 2)',
      page: 2,
      x: 10.5,
      y: 14.2,
      width: 79.0,
      height: 37.5,
      placeholder: 'Additional detailed notes, technical specifications, ideas...',
      fontSize: 12,
      lineHeight: 1.35,
    },
    // Project Budget
    {
      id: 'p2_budget',
      type: 'text',
      label: 'Project Budget',
      page: 2,
      x: 24.0,
      y: 56.61,
      width: 65.5,
      height: 2.3,
      placeholder: 'e.g. 50,000 EUR',
    },
    // Deadline
    {
      id: 'p2_deadline',
      type: 'text',
      label: 'Deadline',
      page: 2,
      x: 19.0,
      y: 60.85,
      width: 70.5,
      height: 2.3,
      placeholder: 'e.g. November 2026 / Week 44',
    },
    // Sales Season: Q1
    {
      id: 'p2_season_q1',
      type: 'checkbox',
      label: 'Sales Season Q1',
      page: 2,
      x: 24.5,
      y: 64.92,
      width: 4.2,
      height: 2.97,
    },
    // Sales Season: Q2
    {
      id: 'p2_season_q2',
      type: 'checkbox',
      label: 'Sales Season Q2',
      page: 2,
      x: 30.5,
      y: 64.92,
      width: 4.2,
      height: 2.97,
    },
    // Sales Season: Q3
    {
      id: 'p2_season_q3',
      type: 'checkbox',
      label: 'Sales Season Q3',
      page: 2,
      x: 36.5,
      y: 64.92,
      width: 4.2,
      height: 2.97,
    },
    // Sales Season: Q4
    {
      id: 'p2_season_q4',
      type: 'checkbox',
      label: 'Sales Season Q4',
      page: 2,
      x: 42.5,
      y: 64.92,
      width: 4.2,
      height: 2.97,
    },
    // Project Type: City
    {
      id: 'p2_type_city',
      type: 'checkbox',
      label: 'Type: City',
      page: 2,
      x: 24.5,
      y: 69.38,
      width: 1.8,
      height: 1.27,
    },
    // Project Type: Shopping Center
    {
      id: 'p2_type_shopping',
      type: 'checkbox',
      label: 'Type: Shopping Center',
      page: 2,
      x: 34.2,
      y: 69.38,
      width: 1.8,
      height: 1.27,
    },
    // Project Type: Other
    {
      id: 'p2_type_other',
      type: 'checkbox',
      label: 'Type: Other',
      page: 2,
      x: 48.7,
      y: 69.38,
      width: 1.8,
      height: 1.27,
    },
    // Project Type: Other text box
    {
      id: 'p2_type_other_text',
      type: 'text',
      label: 'Type: Other (description)',
      page: 2,
      x: 60.5,
      y: 69.02,
      width: 29.0,
      height: 3.39,
      placeholder: 'Description of other project type...',
    },
    // Project Type: Event
    {
      id: 'p2_type_event',
      type: 'checkbox',
      label: 'Type: Event',
      page: 2,
      x: 24.5,
      y: 72.00,
      width: 1.8,
      height: 1.27,
    },
    // Project Type: Hotel / Resort
    {
      id: 'p2_type_hotel',
      type: 'checkbox',
      label: 'Type: Hotel / Resort',
      page: 2,
      x: 34.2,
      y: 72.00,
      width: 1.8,
      height: 1.27,
    },
    // Project Type: Retail Chain
    {
      id: 'p2_type_retail',
      type: 'checkbox',
      label: 'Type: Retail Chain',
      page: 2,
      x: 48.7,
      y: 72.00,
      width: 1.8,
      height: 1.27,
    },
    // Survey Row 1 Checkboxes
    {
      id: 'p2_s1_price',
      type: 'checkbox',
      label: 'S1 Price',
      page: 2,
      x: 11.0,
      y: 80.90,
      width: 1.8,
      height: 1.27,
    },
    {
      id: 'p2_s1_quality',
      type: 'checkbox',
      label: 'S1 Quality',
      page: 2,
      x: 19.5,
      y: 80.90,
      width: 1.8,
      height: 1.27,
    },
    {
      id: 'p2_s1_speed',
      type: 'checkbox',
      label: 'S1 Production speed',
      page: 2,
      x: 28.4,
      y: 80.90,
      width: 1.8,
      height: 1.27,
    },
    {
      id: 'p2_s1_design',
      type: 'checkbox',
      label: 'S1 Design',
      page: 2,
      x: 43.5,
      y: 80.90,
      width: 1.8,
      height: 1.27,
    },
    {
      id: 'p2_s1_other',
      type: 'checkbox',
      label: 'S1 Other',
      page: 2,
      x: 52.4,
      y: 80.90,
      width: 1.8,
      height: 1.27,
    },
    // Survey 1 ranking box (1, 2)
    {
      id: 'p2_s1_rank_box',
      type: 'text',
      label: 'S1 Ranking (1, 2)',
      page: 2,
      x: 60.5,
      y: 80.06,
      width: 29.0,
      height: 2.97,
      placeholder: 'e.g. 1: Quality, 2: Design',
    },
    // Survey Row 2 Checkboxes
    {
      id: 'p2_s2_price',
      type: 'checkbox',
      label: 'S2 Price',
      page: 2,
      x: 11.0,
      y: 85.86,
      width: 1.8,
      height: 1.27,
    },
    {
      id: 'p2_s2_quality',
      type: 'checkbox',
      label: 'S2 Quality',
      page: 2,
      x: 19.5,
      y: 85.86,
      width: 1.8,
      height: 1.27,
    },
    {
      id: 'p2_s2_speed',
      type: 'checkbox',
      label: 'S2 Production speed',
      page: 2,
      x: 28.4,
      y: 85.86,
      width: 1.8,
      height: 1.27,
    },
    {
      id: 'p2_s2_design',
      type: 'checkbox',
      label: 'S2 Design',
      page: 2,
      x: 43.5,
      y: 85.86,
      width: 1.8,
      height: 1.27,
    },
    {
      id: 'p2_s2_other',
      type: 'checkbox',
      label: 'S2 Other',
      page: 2,
      x: 52.4,
      y: 85.86,
      width: 1.8,
      height: 1.27,
    },
    // Survey 2 ranking box
    {
      id: 'p2_s2_rank_box',
      type: 'text',
      label: 'S2 Ranking',
      page: 2,
      x: 60.5,
      y: 84.87,
      width: 29.0,
      height: 2.97,
      placeholder: 'Enter remarks / ranking...',
    },
    // Survey Row 3 Checkboxes
    {
      id: 'p2_s3_price',
      type: 'checkbox',
      label: 'S3 Price',
      page: 2,
      x: 11.0,
      y: 90.45,
      width: 1.8,
      height: 1.27,
    },
    {
      id: 'p2_s3_quality',
      type: 'checkbox',
      label: 'S3 Quality',
      page: 2,
      x: 19.5,
      y: 90.45,
      width: 1.8,
      height: 1.27,
    },
    {
      id: 'p2_s3_speed',
      type: 'checkbox',
      label: 'S3 Production speed',
      page: 2,
      x: 28.4,
      y: 90.45,
      width: 1.8,
      height: 1.27,
    },
    {
      id: 'p2_s3_design',
      type: 'checkbox',
      label: 'S3 Design',
      page: 2,
      x: 43.5,
      y: 90.45,
      width: 1.8,
      height: 1.27,
    },
    {
      id: 'p2_s3_other',
      type: 'checkbox',
      label: 'S3 Other',
      page: 2,
      x: 52.4,
      y: 90.45,
      width: 1.8,
      height: 1.27,
    },
    // Survey 3 ranking box
    {
      id: 'p2_s3_rank_box',
      type: 'text',
      label: 'S3 Ranking',
      page: 2,
      x: 60.5,
      y: 89.53,
      width: 29.0,
      height: 2.97,
      placeholder: 'Enter suggestions for improvement...',
    },
  ];
}

export function createAdalGuestBookTemplate(): FormTemplate {
  const now = new Date().toISOString();
  return {
    id: ADAL_TEMPLATE_ID,
    name: 'GUEST BOOK 2026 - MAPIC (Adal decorations)',
    description: 'The official Adal decorations fair form: 2 A4 pages with project sketch, notes, budget, and survey.',
    fileName: '2026_Targi_MAPIC_GuestBook_Adal_02_Formularz.pdf',
    pageCount: 2,
    pageAspectRatios: [1.4142, 1.4142], // Standard A4 ratio (297mm / 210mm)
    fields: getAdalDefaultFields(),
    createdAt: now,
    updatedAt: now,
  };
}
