import { FormField, FormTemplate } from '../types';

export const ADAL_TEMPLATE_ID = 'adal_guest_book_2026';

export function getAdalDefaultFields(): FormField[] {
  return [
    // -------------------------------------------------------------
    // PAGE 1 FIELDS
    // -------------------------------------------------------------
    // Top-Right PROJECT box: drawing / sketch / photo / text area
    {
      id: 'p1_project_box',
      type: 'signature', // allows tablet pen/finger drawing & sketch
      label: 'Szkic / Notatka projektu (PROJECT)',
      page: 1,
      x: 47.0,
      y: 4.2,
      width: 42.5,
      height: 18.2,
      placeholder: 'Kliknij lub użyj rysika / palca, aby naszkicować projekt...',
    },
    // Date
    {
      id: 'p1_date',
      type: 'text',
      label: 'Data (Date)',
      page: 1,
      x: 15.0,
      y: 24.5,
      width: 23.5,
      height: 2.6,
      placeholder: 'np. 04.11.2026',
    },
    // Contact Person
    {
      id: 'p1_contact_person',
      type: 'text',
      label: 'Osoba kontaktowa (Contact Person)',
      page: 1,
      x: 54.0,
      y: 24.5,
      width: 35.5,
      height: 2.6,
      placeholder: 'Imię i nazwisko',
    },
    // Country
    {
      id: 'p1_country',
      type: 'text',
      label: 'Kraj (Country)',
      page: 1,
      x: 18.0,
      y: 28.5,
      width: 24.0,
      height: 2.6,
      placeholder: 'np. Polska / France',
    },
    // Company Name
    {
      id: 'p1_company_name',
      type: 'text',
      label: 'Nazwa firmy (Company Name)',
      page: 1,
      x: 57.5,
      y: 28.5,
      width: 32.0,
      height: 2.6,
      placeholder: 'Nazwa firmy',
    },
    // Email
    {
      id: 'p1_email',
      type: 'text',
      label: 'E-mail',
      page: 1,
      x: 15.5,
      y: 32.5,
      width: 33.5,
      height: 2.6,
      placeholder: 'jan@firma.pl',
    },
    // Phone
    {
      id: 'p1_phone',
      type: 'text',
      label: 'Telefon (Phone)',
      page: 1,
      x: 56.5,
      y: 32.5,
      width: 33.0,
      height: 2.6,
      placeholder: '+48 600 000 000',
    },
    // Catalogue to send: Digital
    {
      id: 'p1_cat_digital',
      type: 'checkbox',
      label: 'Digital catalogue',
      page: 1,
      x: 28.7,
      y: 37.6,
      width: 2.3,
      height: 1.8,
    },
    // Catalogue to send: Printed
    {
      id: 'p1_cat_printed',
      type: 'checkbox',
      label: 'Printed catalogue',
      page: 1,
      x: 38.6,
      y: 37.6,
      width: 2.3,
      height: 1.8,
    },
    // Catalogue: Christmas trees & greenery products
    {
      id: 'p1_cat_trees',
      type: 'checkbox',
      label: 'Christmas trees & greenery',
      page: 1,
      x: 50.8,
      y: 37.6,
      width: 2.3,
      height: 1.8,
    },
    // Catalogue: Decor products
    {
      id: 'p1_cat_decor',
      type: 'checkbox',
      label: 'Decor products',
      page: 1,
      x: 77.2,
      y: 37.6,
      width: 2.3,
      height: 1.8,
    },
    // Adress line 1
    {
      id: 'p1_address_1',
      type: 'text',
      label: 'Adress line 1',
      page: 1,
      x: 22.0,
      y: 40.5,
      width: 67.5,
      height: 2.6,
      placeholder: 'Ulica, numer lokalu...',
    },
    // Adress line 2
    {
      id: 'p1_address_2',
      type: 'text',
      label: 'Adress line 2',
      page: 1,
      x: 22.0,
      y: 44.5,
      width: 67.5,
      height: 2.6,
      placeholder: 'Kod pocztowy, miasto...',
    },
    // Are you interested in seasonal decorations?: Yes
    {
      id: 'p1_seasonal_yes',
      type: 'checkbox',
      label: 'Seasonal: Yes',
      page: 1,
      x: 52.8,
      y: 49.0,
      width: 2.3,
      height: 1.8,
    },
    // Are you interested in seasonal decorations?: No
    {
      id: 'p1_seasonal_no',
      type: 'checkbox',
      label: 'Seasonal: No',
      page: 1,
      x: 61.1,
      y: 49.0,
      width: 2.3,
      height: 1.8,
    },
    // Seasonal: Valentine’s Day
    {
      id: 'p1_seasonal_val',
      type: 'checkbox',
      label: "Valentine's Day",
      page: 1,
      x: 10.8,
      y: 52.6,
      width: 2.3,
      height: 1.8,
    },
    // Seasonal: Easter
    {
      id: 'p1_seasonal_easter',
      type: 'checkbox',
      label: 'Easter',
      page: 1,
      x: 27.5,
      y: 52.6,
      width: 2.3,
      height: 1.8,
    },
    // Seasonal: Spring
    {
      id: 'p1_seasonal_spring',
      type: 'checkbox',
      label: 'Spring',
      page: 1,
      x: 41.5,
      y: 52.6,
      width: 2.3,
      height: 1.8,
    },
    // Seasonal: Summer
    {
      id: 'p1_seasonal_summer',
      type: 'checkbox',
      label: 'Summer',
      page: 1,
      x: 54.5,
      y: 52.6,
      width: 2.3,
      height: 1.8,
    },
    // Seasonal: Halloween
    {
      id: 'p1_seasonal_halloween',
      type: 'checkbox',
      label: 'Halloween',
      page: 1,
      x: 67.8,
      y: 52.6,
      width: 2.3,
      height: 1.8,
    },
    // Seasonal: Autumn
    {
      id: 'p1_seasonal_autumn',
      type: 'checkbox',
      label: 'Autumn',
      page: 1,
      x: 82.2,
      y: 52.6,
      width: 2.3,
      height: 1.8,
    },
    // Would you like to visit showroom?: Yes
    {
      id: 'p1_visit_yes',
      type: 'checkbox',
      label: 'Visit showroom: Yes',
      page: 1,
      x: 52.8,
      y: 56.6,
      width: 2.3,
      height: 1.8,
    },
    // Would you like to visit showroom?: No
    {
      id: 'p1_visit_no',
      type: 'checkbox',
      label: 'Visit showroom: No',
      page: 1,
      x: 61.1,
      y: 56.6,
      width: 2.3,
      height: 1.8,
    },
    // Preferred time period
    {
      id: 'p1_visit_period',
      type: 'text',
      label: 'Preferred time period',
      page: 1,
      x: 41.5,
      y: 59.8,
      width: 48.0,
      height: 2.5,
      placeholder: 'np. Wiosna 2027 / Q2',
    },
    // Page 1 Notes / Project Ideas textarea
    {
      id: 'p1_notes',
      type: 'textarea',
      label: 'Notes / Project Ideas (Strona 1)',
      page: 1,
      x: 10.0,
      y: 66.5,
      width: 79.5,
      height: 25.5,
      placeholder: 'Wpisz notatki i pomysły projektowe klienta...',
      fontSize: 12,
      lineHeight: 1.35,
    },

    // -------------------------------------------------------------
    // PAGE 2 FIELDS
    // -------------------------------------------------------------
    // Page 2 Notes / Project Ideas
    {
      id: 'p2_notes',
      type: 'textarea',
      label: 'Notes / Project Ideas (Strona 2)',
      page: 2,
      x: 10.0,
      y: 15.0,
      width: 79.5,
      height: 36.5,
      placeholder: 'Dodatkowe szczegółowe notatki, ustalenia techniczne, szkice...',
      fontSize: 12,
      lineHeight: 1.35,
    },
    // Project Budget
    {
      id: 'p2_budget',
      type: 'text',
      label: 'Project Budget',
      page: 2,
      x: 23.5,
      y: 56.5,
      width: 66.0,
      height: 2.6,
      placeholder: 'np. 50 000 EUR',
    },
    // Deadline
    {
      id: 'p2_deadline',
      type: 'text',
      label: 'Deadline',
      page: 2,
      x: 19.0,
      y: 60.8,
      width: 70.5,
      height: 2.6,
      placeholder: 'np. Listopad 2026',
    },
    // Sales Season: Q1
    {
      id: 'p2_season_q1',
      type: 'checkbox',
      label: 'Sales Season Q1',
      page: 2,
      x: 24.5,
      y: 63.8,
      width: 4.2,
      height: 3.2,
    },
    // Sales Season: Q2
    {
      id: 'p2_season_q2',
      type: 'checkbox',
      label: 'Sales Season Q2',
      page: 2,
      x: 30.5,
      y: 63.8,
      width: 4.2,
      height: 3.2,
    },
    // Sales Season: Q3
    {
      id: 'p2_season_q3',
      type: 'checkbox',
      label: 'Sales Season Q3',
      page: 2,
      x: 36.5,
      y: 63.8,
      width: 4.2,
      height: 3.2,
    },
    // Sales Season: Q4
    {
      id: 'p2_season_q4',
      type: 'checkbox',
      label: 'Sales Season Q4',
      page: 2,
      x: 42.5,
      y: 63.8,
      width: 4.2,
      height: 3.2,
    },
    // Project Type: City
    {
      id: 'p2_type_city',
      type: 'checkbox',
      label: 'Type: City',
      page: 2,
      x: 24.2,
      y: 68.0,
      width: 2.3,
      height: 1.8,
    },
    // Project Type: Shopping Center
    {
      id: 'p2_type_shopping',
      type: 'checkbox',
      label: 'Type: Shopping Center',
      page: 2,
      x: 34.0,
      y: 68.0,
      width: 2.3,
      height: 1.8,
    },
    // Project Type: Other
    {
      id: 'p2_type_other',
      type: 'checkbox',
      label: 'Type: Other',
      page: 2,
      x: 48.5,
      y: 68.0,
      width: 2.3,
      height: 1.8,
    },
    // Project Type: Other text box
    {
      id: 'p2_type_other_text',
      type: 'text',
      label: 'Type: Inne (opis)',
      page: 2,
      x: 60.5,
      y: 67.8,
      width: 29.0,
      height: 3.4,
      placeholder: 'Opis innego typu...',
    },
    // Project Type: Event
    {
      id: 'p2_type_event',
      type: 'checkbox',
      label: 'Type: Event',
      page: 2,
      x: 24.2,
      y: 70.5,
      width: 2.3,
      height: 1.8,
    },
    // Project Type: Hotel / Resort
    {
      id: 'p2_type_hotel',
      type: 'checkbox',
      label: 'Type: Hotel / Resort',
      page: 2,
      x: 34.0,
      y: 70.5,
      width: 2.3,
      height: 1.8,
    },
    // Project Type: Retail Chain
    {
      id: 'p2_type_retail',
      type: 'checkbox',
      label: 'Type: Retail Chain',
      page: 2,
      x: 48.5,
      y: 70.5,
      width: 2.3,
      height: 1.8,
    },
    // Survey Row 1 Checkboxes
    {
      id: 'p2_s1_price',
      type: 'checkbox',
      label: 'S1 Price',
      page: 2,
      x: 10.8,
      y: 80.2,
      width: 2.3,
      height: 1.8,
    },
    {
      id: 'p2_s1_quality',
      type: 'checkbox',
      label: 'S1 Quality',
      page: 2,
      x: 19.3,
      y: 80.2,
      width: 2.3,
      height: 1.8,
    },
    {
      id: 'p2_s1_speed',
      type: 'checkbox',
      label: 'S1 Production speed',
      page: 2,
      x: 28.2,
      y: 80.2,
      width: 2.3,
      height: 1.8,
    },
    {
      id: 'p2_s1_design',
      type: 'checkbox',
      label: 'S1 Design',
      page: 2,
      x: 43.3,
      y: 80.2,
      width: 2.3,
      height: 1.8,
    },
    {
      id: 'p2_s1_other',
      type: 'checkbox',
      label: 'S1 Other',
      page: 2,
      x: 52.2,
      y: 80.2,
      width: 2.3,
      height: 1.8,
    },
    // Survey 1 ranking box (1, 2)
    {
      id: 'p2_s1_rank_box',
      type: 'text',
      label: 'S1 Ranking (1, 2)',
      page: 2,
      x: 60.5,
      y: 79.2,
      width: 29.0,
      height: 3.2,
      placeholder: 'Wpisz np. 1: Quality, 2: Design',
    },
    // Survey Row 2 Checkboxes
    {
      id: 'p2_s2_price',
      type: 'checkbox',
      label: 'S2 Price',
      page: 2,
      x: 10.8,
      y: 85.0,
      width: 2.3,
      height: 1.8,
    },
    {
      id: 'p2_s2_quality',
      type: 'checkbox',
      label: 'S2 Quality',
      page: 2,
      x: 19.3,
      y: 85.0,
      width: 2.3,
      height: 1.8,
    },
    {
      id: 'p2_s2_speed',
      type: 'checkbox',
      label: 'S2 Production speed',
      page: 2,
      x: 28.2,
      y: 85.0,
      width: 2.3,
      height: 1.8,
    },
    {
      id: 'p2_s2_design',
      type: 'checkbox',
      label: 'S2 Design',
      page: 2,
      x: 43.3,
      y: 85.0,
      width: 2.3,
      height: 1.8,
    },
    {
      id: 'p2_s2_other',
      type: 'checkbox',
      label: 'S2 Other',
      page: 2,
      x: 52.2,
      y: 85.0,
      width: 2.3,
      height: 1.8,
    },
    // Survey 2 ranking box
    {
      id: 'p2_s2_rank_box',
      type: 'text',
      label: 'S2 Ranking',
      page: 2,
      x: 60.5,
      y: 83.8,
      width: 29.0,
      height: 3.2,
      placeholder: 'Wpisz uwagi / ranking...',
    },
    // Survey Row 3 Checkboxes
    {
      id: 'p2_s3_price',
      type: 'checkbox',
      label: 'S3 Price',
      page: 2,
      x: 10.8,
      y: 89.6,
      width: 2.3,
      height: 1.8,
    },
    {
      id: 'p2_s3_quality',
      type: 'checkbox',
      label: 'S3 Quality',
      page: 2,
      x: 19.3,
      y: 89.6,
      width: 2.3,
      height: 1.8,
    },
    {
      id: 'p2_s3_speed',
      type: 'checkbox',
      label: 'S3 Production speed',
      page: 2,
      x: 28.2,
      y: 89.6,
      width: 2.3,
      height: 1.8,
    },
    {
      id: 'p2_s3_design',
      type: 'checkbox',
      label: 'S3 Design',
      page: 2,
      x: 43.3,
      y: 89.6,
      width: 2.3,
      height: 1.8,
    },
    {
      id: 'p2_s3_other',
      type: 'checkbox',
      label: 'S3 Other',
      page: 2,
      x: 52.2,
      y: 89.6,
      width: 2.3,
      height: 1.8,
    },
    // Survey 3 ranking box
    {
      id: 'p2_s3_rank_box',
      type: 'text',
      label: 'S3 Ranking',
      page: 2,
      x: 60.5,
      y: 88.4,
      width: 29.0,
      height: 3.2,
      placeholder: 'Wpisz uwagi / propozycje poprawy...',
    },
  ];
}

export function createAdalGuestBookTemplate(): FormTemplate {
  const now = new Date().toISOString();
  return {
    id: ADAL_TEMPLATE_ID,
    name: 'GUEST BOOK 2026 - MAPIC (Adal decorations)',
    description: 'Jedyny oficjalny formularz targowy Adal decorations: 2 strony A4 z polami projektu, notatkami, budżetem i ankietą.',
    fileName: 'Adal_Guest_Book_2026_MAPIC.pdf',
    pageCount: 2,
    pageAspectRatios: [1.4142, 1.4142], // Standard A4 ratio (297mm / 210mm)
    fields: getAdalDefaultFields(),
    createdAt: now,
    updatedAt: now,
  };
}
